services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    init: true
    volumes:
      - ..:/workspaces/today:cached
    command: sleep infinity
    environment:
      - DEVCONTAINER_PROJECT=today
